Authentication and storage API
scorelab/gocloud-v2 pull request #7
Opened 2017-06-25 13:13 UTC by PratikDhanave

2017-06-25 13:33 UTC, rehrumesh commented
@PratikDhanave please look at the code quality report of codacy.

2017-06-25 13:41 UTC, PratikDhanave commented
Yes Need some time to update.

On Sun, Jun 25, 2017 at 7:03 PM, Rumesh Eranga Hapuarachchi <
notifications@github.com> wrote:

> @PratikDhanave <https://github.com/pratikdhanave> please look at the code
> quality report of codacy.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/scorelab/gocloud-v2/pull/7#issuecomment-310902910>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ACFKH9TbqfHOEcO9ywE1gIKWmFcmn5psks5sHmGugaJpZM4OEmpt>
> .
>

2017-06-30 02:57 UTC, rehrumesh commented on compute/ec2/instance.go
> +	//"log"
remove unwanted lines

2017-06-30 02:58 UTC, rehrumesh commented on compute/ec2/instance.go
> +	//fmt.Println(req)
remove unwanted comments

2017-06-30 02:59 UTC, rehrumesh commented on compute/ec2/sign.go
>  func errorCollector(writers ...func() error) error {
remove this part

2017-06-30 03:00 UTC, rehrumesh commented on compute/gce/instance.go
> +	//respq := GCEResponse{}
remove unwanted comments.

2017-06-30 03:01 UTC, rehrumesh commented on main.go
> +		InitializeParams := map[string]string{
Remove this block

2017-06-30 03:01 UTC, rehrumesh commented on storage/amazonstorage/storage.go
> +	//"log"
remove unwanted comments

2017-06-30 03:01 UTC, rehrumesh commented on storage/googlestorage/googlestorage.go
> +type Snapshot struct {
Remove this block

2017-06-30 03:02 UTC, rehrumesh requested changes
Please do the necessary changes to the comments

2017-06-30 03:03 UTC, rehrumesh commented
@PratikDhanave There are code conflicts and code quality issues. Fix them asap so we can close this PR.

2017-07-05 16:36 UTC, rehrumesh requested changes
update with requests

2017-07-05 16:43 UTC, closed without merging